### GET request to example server
GET https://examples.http-client.intellij.net/get
    ?generated-in=IntelliJ IDEA

###
POST localhost:8080/auth/signup
Content-Type: application/json

{
  "email": "zxc@google.com",
  "password": "1234",
  "userRole": "ADMIN",
  "nickName": "관리자"
}
###
POST localhost:8080/auth/signin
Content-Type: application/json

{
  "email": "abc@google.com",
  "password": "1234"
}
> {%

    client.global.set("accessToken", response.body.bearerToken);
%}
###
POST localhost:8080/todos
Content-Type: application/json
Authorization: {{accessToken}}

{
  "title": "제목8",
  "contents": "할일"
}
###
GET localhost:8080/todos/search?weather=glaze
Authorization: {{accessToken}}

###
GET localhost:8080/users/1
Authorization: {{accessToken}}

###
PATCH localhost:8080/admin/users/3
Content-Type: application/json
Authorization: {{accessToken}}

{
  "role": "USER"
}
###
POST localhost:8080/todos/8/comments
Authorization: {{accessToken}}
Content-Type: application/json

{
  "contents": "아자차"
}

###
GET localhost:8080/todos/8/comments
Authorization: {{accessToken}}


###


